<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Permission::truncate();
        Schema::enableForeignKeyConstraints();
        $permissions = collect([
            ['name' => 'global-user', 'description' => "afficher tout des utilisateurs"],
            ['name' => 'own-user', 'description' => "afficher uniquement les utilisateurs crées par l'utilisateur connecté"],
            ['name' => 'create-user', 'description' => "créer un utilisateur"],
            ['name' => 'trash-user', 'description' => "archiver un utilisateur"],
            ['name' => 'restore-user', 'description' => "restaurer un utilisateur déjà archivé"],
            ['name' => 'delete-user', 'description' => "supprimer définitivement un utilisateur"],
            ['name' => 'edit-user', 'description' => "modifier un utilisateur"],
            ['name' => 'show-user', 'description' => "afficher les informations détaillées d'un utilisateur"],
            ['name' => 'attribuate-role-user', 'description' => "attribuer un role à un utiisateur"],
            ['name' => 'list-role', 'description' => "afficher la liste des rôles"],
            ['name' => 'trash-role', 'description' => "archiver un rôle"],
            ['name' => 'create-role', 'description' => "créer un rôle"],
            ['name' => 'restore-role', 'description' => "restaurer un rôle"],
            ['name' => 'edit-role', 'description' => "modifier un rôle"],
            ['name' => 'list-permission', 'description' => "afficher la liste des permissions"],
            ['name' => 'edit-permission', 'description' => "modifier une permission"],
            ['name' => 'global-site', 'description' => "afficher tout d'un site"],
            ['name' => 'own-site', 'description' => "afficher uniquement les sites crées par l'utilisateur connecté"],
            ['name' => 'trash-site', 'description' => "archiver un site"],
            ['name' => 'delete-site', 'description' => "supprimer définitivement un site"],
            ['name' => 'edit-site', 'description' => "modifier un site"],
            ['name' => 'show-site', 'description' => "afficher les informations détaillées d'un site"],
            ['name' => 'global-pavillon', 'description' => "afficher tout les pavillons"],
            ['name' => 'own-pavillon', 'description' => "afficher uniquement les pavillons crées par l'utilisateur connecté"],
            ['name' => 'create-pavillon', 'description' => "créer un pavillon"],
            ['name' => 'trash-pavillon', 'description' => "archiver un pavillon"],
            ['name' => 'restore-pavillon', 'description' => "restaurer un pavillon archivé"],
            ['name' => 'delete-pavillon', 'description' => "supprimer un pavillon"],
            ['name' => 'edit-pavillon', 'description' => "modifier un pavillon"],
            ['name' => 'global-niveau', 'description' => "afficher tout les niveaux"],
            ['name' => 'own-niveau', 'description' => "afficher uniquement les niveaux crées par l'utilisateur connecté"],
            ['name' => 'create-niveau', 'description' => "créer un niveau"],
            ['name' => 'trash-niveau', 'description' => "archiver un niveau"],
            ['name' => 'restore-niveau', 'description' => "restaurer un niveau archivé"],
            ['name' => 'delete-niveau', 'description' => "supprimer un niveau"],
            ['name' => 'edit-niveau', 'description' => "modifier un niveau"],
            ['name' => 'global-zone', 'description' => "afficher tout les zone"],
            ['name' => 'own-zone', 'description' => "afficher uniquement les zones crées par l'utilisateur connecté"],
            ['name' => 'create-zone', 'description' => "créer une zone"],
            ['name' => 'trash-zone', 'description' => "archiver une zone"],
            ['name' => 'restore-zone', 'description' => "restaurer une zone archivée"],
            ['name' => 'delete-zone', 'description' => "supprimer une zone"],
            ['name' => 'edit-zone', 'description' => "modifier une zone"],
            ['name' => 'global-emplacement', 'description' => "afficher tout les emplacements"],
            ['name' => 'own-emplacement', 'description' => "afficher uniquement les emplacements crées par l'utilisateur connecté"],
            ['name' => 'create-emplacement', 'description' => "créer un emplacement"],
            ['name' => 'trash-emplacement', 'description' => "archiver un emplacement"],
            ['name' => 'restore-emplacement', 'description' => "restaurer un emplacement archivé"],
            ['name' => 'delete-emplacement', 'description' => "supprimer un emplacement"],
            ['name' => 'edit-emplacement', 'description' => "modifier un emplacement"],
            ['name' => 'show-emplacement', 'description' => "afficher les informations détaillées d'un emplacement"],
            ['name' => 'global-equipement', 'description' => "afficher tout les equipements"],
            ['name' => 'own-equipement', 'description' => "afficher uniquement les equipements crées par l'utilisateur connecté"],
            ['name' => 'create-equipement', 'description' => "créer un equipement"],
            ['name' => 'trash-equipement', 'description' => "archiver un equipement"],
            ['name' => 'restore-equipement', 'description' => "restaurer un equipement archivé"],
            ['name' => 'delete-equipement', 'description' => "supprimer définitivement un equipement"],
            ['name' => 'edit-equipement', 'description' => "modifier un equipement"],
            ['name' => 'show-equipement', 'description' => "afficher les informations détaillées d'un equipement"],
            ['name' => 'global-abonnement', 'description' => "afficher tout les abonnements"],
            ['name' => 'own-abonnement', 'description' => "afficher uniquement les abonnements crées par l'utilisateur connecté"],
            ['name' => 'create-abonnement', 'description' => "créer un abonnement"],
            ['name' => 'trash-abonnement', 'description' => "archiver un abonnement"],
            ['name' => 'restore-abonnement', 'description' => "restaurer un abonnement archivé"],
            ['name' => 'delete-abonnement', 'description' => "supprimer définitivement un abonnement"],
            ['name' => 'edit-abonnement', 'description' => "modifier un abonnement"],
            ['name' => 'show-abonnement', 'description' => "afficher les informations détaillées d'un abonnement"],
            ['name' => 'abort-abonnement', 'description' => "résilier un abonnement"],
            ['name' => 'global-type-equipement', 'description' => "afficher tout les types d'equipements"],
            ['name' => 'own-type-equipement', 'description' => "afficher uniquement les types d'equipements crées par l'utilisateur connecté"],
            ['name' => 'create-type-equipement', 'description' => "créer un type d'equipement"],
            ['name' => 'trash-type-equipement', 'description' => "archiver un type d'equipement"],
            ['name' => 'restore-type-equipement', 'description' => "restaurer un type d'equipement archivé"],
            ['name' => 'delete-type-equipement', 'description' => "supprimer un type d'equipement"],
            ['name' => 'edit-type-equipement', 'description' => "modifier un type d'equipement"],
            ['name' => 'global-type-personne', 'description' => "afficher tout les types de prospects/clients"],
            ['name' => 'own-type-personne', 'description' => "afficher uniquement les types de prospects/clients crées par l'utilisateur connecté"],
            ['name' => 'create-type-personne', 'description' => "créer un type de prospect/client"],
            ['name' => 'trash-type-personne', 'description' => "archiver un type de prospect/client"],
            ['name' => 'restore-type-personne', 'description' => "restaurer un type de prospect/client archivé"],
            ['name' => 'delete-type-personne', 'description' => "supprimer un type de prospect/client"],
            ['name' => 'edit-type-personne', 'description' => "modifier un type de prospect/client"],
            ['name' => 'global-type-emplacement', 'description' => "afficher tout les types d'emplacements"],
            ['name' => 'own-type-emplacement', 'description' => "afficher uniquement les types d'emplacements crées par l'utilisateur connecté"],
            ['name' => 'create-type-emplacement', 'description' => "créer un type d'emplacement"],
            ['name' => 'trash-type-emplacement', 'description' => "archiver un type d'emplacement"],
            ['name' => 'restore-type-emplacement', 'description' => "restaurer un type d'emplacement archivé"],
            ['name' => 'delete-type-emplacement', 'description' => "supprimer un type d'emplacement"],
            ['name' => 'edit-type-emplacement', 'description' => "modifier un type d'emplacement"],
            ['name' => 'global-annexe', 'description' => "afficher tout les services annexes"],
            ['name' => 'own-annexe', 'description' => "afficher uniquement les services annexes crées par l'utilisateur connecté"],
            ['name' => 'create-annexe', 'description' => "créer un service annexe"],
            ['name' => 'trash-annexe', 'description' => "archiver un service annexe"],
            ['name' => 'restore-annexe', 'description' => "restaurer un service annexe archivé"],
            ['name' => 'delete-annexe', 'description' => "supprimer un service annexe"],
            ['name' => 'edit-annexe', 'description' => "modifier un service annexe"],
            ['name' => 'show-annexe', 'description' => "afficher les informations détaillées d'un service annexe"],
            ['name' => 'global-guichet', 'description' => "afficher tout les guichets"],
            ['name' => 'own-guichet', 'description' => "afficher uniquement les guichets crées par l'utilisateur connecté"],
            ['name' => 'create-guichet', 'description' => "créer un guichet"],
            ['name' => 'trash-guichet', 'description' => "archiver un guichet"],
            ['name' => 'restore-guichet', 'description' => "restaurer un guichet archivé"],
            ['name' => 'delete-guichet', 'description' => "supprimer un guichet"],
            ['name' => 'edit-guichet', 'description' => "modifier un guichet"],
            ['name' => 'show-guichet', 'description' => "afficher les informations détaillées d'un guichet"],
            ['name' => 'global-caissier', 'description' => "afficher tout les caissiers"],
            ['name' => 'own-caissier', 'description' => "afficher uniquement les caissiers crées par l'utilisateur connecté"],
            ['name' => 'create-caissier', 'description' => "créer un caissier"],
            ['name' => 'trash-caissier', 'description' => "archiver un caissier"],
            ['name' => 'restore-caissier', 'description' => "restaurer un caissier archivé"],
            ['name' => 'edit-caissier', 'description' => "modifier un caissier"],
            ['name' => 'show-caissier', 'description' => "afficher les informations détaillées d'un caissier"],
            ['name' => 'attribuate-caissier', 'description' => "attribuer des guichets à un caissier"],
            ['name' => 'global-compte', 'description' => "afficher tout les comptes"],
            ['name' => 'own-compte', 'description' => "afficher uniquement les comptes crées par l'utilisateur connecté"],
            ['name' => 'create-compte', 'description' => "créer un compte"],
            ['name' => 'edit-compte', 'description' => "modifier un compte"],
            ['name' => 'global-banque', 'description' => "afficher toute les banques"],
            ['name' => 'own-banque', 'description' => "afficher uniquement les banques crées par l'utilisateur connecté"],
            ['name' => 'create-banque', 'description' => "créer une banque"],
            ['name' => 'trash-banque', 'description' => "archiver une banque"],
            ['name' => 'restore-banque', 'description' => "restaurer un banque archivé"],
            ['name' => 'delete-banque', 'description' => "supprimer définitivement une banque"],
            ['name' => 'edit-banque', 'description' => "modifier une banque"],
            ['name' => 'list-application', 'description' => "afficher les informations de la société"],
            ['name' => 'edit-application', 'description' => "modifier les informations de la société"],
            ['name' => 'list-gabari-contrat', 'description' => "afficher tout les gabaris de contrats"],
            ['name' => 'create-gabari-contrat', 'description' => "créer un gabari de contrat"],
            ['name' => 'trash-gabari-contrat', 'description' => "archiver un gabari de contrat"],
            ['name' => 'restore-gabari-contrat', 'description' => "restaurer un gabari de contrat archivé"],
            ['name' => 'delete-gabari-contrat', 'description' => "supprimer définitivement un gabari de contrat"],
            ['name' => 'edit-gabari-contrat', 'description' => "modifier un gabari de contrat"],
            ['name' => 'show-gabari-contrat', 'description' => "afficher les informations détaillées d'un gabari de contrat"],
            ['name' => 'list-reception-dashboard', 'description' => "accéder au dashboard de la reception"],
            ['name' => 'filter-reception-dashboard', 'description' => "filtrer le dashboard de la reception"],
            ['name' => 'global-contrat', 'description' => "afficher tout les contrats/demandes"],
            ['name' => 'own-contrat', 'description' => "afficher uniquement les contrats/demandes crées par l'utilisateur connecté"],
            ['name' => 'create-contrat', 'description' => "créer un contrat/demande"],
            ['name' => 'trash-contrat', 'description' => "archiver un contrat/demande"],
            ['name' => 'restore-contrat', 'description' => "restaurer un contrat/demande archivé"],
            ['name' => 'delete-contrat', 'description' => "supprimer définitivement un contrat/demande"],
            ['name' => 'edit-contrat', 'description' => "modifier un contrat/demande"],
            ['name' => 'show-contrat', 'description' => "afficher les informations détaillées d'un contrat/demande"],
            ['name' => 'schedule-contrat', 'description' => "valider le contrat pour l'ordonnancement"],
            ['name' => 'endorse-contrat', 'description' => "valider le contrat pour signature"],
            ['name' => 'validate-contrat', 'description' => "valider définitivement le contrat"],
            ['name' => 'global-personne', 'description' => "afficher tout les prospects/clients"],
            ['name' => 'own-personne', 'description' => "afficher uniquement les prospects/clients crées par l'utilisateur connecté"],
            ['name' => 'create-personne', 'description' => "créer un prospect/client"],
            ['name' => 'trash-personne', 'description' => "archiver un prospect/client"],
            ['name' => 'restore-personne', 'description' => "restaurer un prospect/client archivé"],
            ['name' => 'delete-personne', 'description' => "supprimer définitivement un prospect/client"],
            ['name' => 'edit-personne', 'description' => "modifier un prospect/client"],
            ['name' => 'show-personne', 'description' => "afficher les informations détaillées d'un prospect/client"],
            ['name' => 'list-ordonnancement-dashboard', 'description' => "accéder au dashboard des ordonnancements"],
            ['name' => 'filter-ordonnancement-dashboard', 'description' => "filtrer le dashboard des ordonnancements"],
            ['name' => 'list-bordereau-dashboard', 'description' => "accéder au dashboard des bordereaux"],
            ['name' => 'filter-bordereau-dashboard', 'description' => "filtrer le dashboard des bordereaux"],
            ['name' => 'list-caisse-dashboard', 'description' => "accéder au dashboard de la caisse"],
            ['name' => 'filter-caisse-dashboard', 'description' => "filtrer le dashboard de la caisse"],
            ['name' => 'list-facture-dashboard', 'description' => "accéder au dashboard des factures"],
            ['name' => 'filter-facture-dashboard', 'description' => "filtrer le dashboard des factures"],
            ['name' => 'global-ordonnancement', 'description' => "afficher tout les ordonnancements"],
            ['name' => 'own-ordonnancement', 'description' => "afficher uniquement les ordonnancements crées par l'utilisateur connecté"],
            ['name' => 'create-ordonnancement', 'description' => "créer un ordonnancement"],
            ['name' => 'show-ordonnancement', 'description' => "afficher les informations détaillées d'un ordonnancement"],
            ['name' => 'edit-ordonnancement', 'description' => "modifié un ordre de recette encore impayé"],
            ['name' => 'global-facture-initiale', 'description' => "afficher toutes les factures PDP"],
            ['name' => 'own-facture-initiale', 'description' => "afficher uniquement les factures PDP crées par l'utilisateur connecté"],
            ['name' => 'show-facture-initiale', 'description' => "afficher les informations détaillées d'une facture PDP"],
            ['name' => 'edit-facture-initiale', 'description' => "modifier une facture PDP"],
            ['name' => 'global-facture-loyer', 'description' => "afficher toutes les facture de loyers"],
            ['name' => 'own-facture-loyer', 'description' => "afficher uniquement les factures de loyers crées par l'utilisateur connecté"],
            ['name' => 'show-facture-loyer', 'description' => "afficher les informations détaillées d'une facture de loyer"],
            ['name' => 'global-facture-annexe', 'description' => "afficher toutes les factures annexes"],
            ['name' => 'own-facture-annexe', 'description' => "afficher uniquement les factures annexes crées par l'utilisateur connecté"],
            ['name' => 'show-facture-annexe', 'description' => "afficher les informations détaillées d'une facture annexe"],
            ['name' => 'global-facture-equipement', 'description' => "afficher toutes les factures d'equipements"],
            ['name' => 'own-facture-equipement', 'description' => "afficher uniquement les factures d'equipements crées par l'utilisateur connecté"],
            ['name' => 'show-facture-equipement', 'description' => "afficher les informations détaillées d'une facture d'equipement"],
            ['name' => 'global-commercial', 'description' => "afficher tout les commerciaux"],
            ['name' => 'own-commercial', 'description' => "afficher uniquement les commerciaux crées par l'utilisateur connecté"],
            ['name' => 'create-commercial', 'description' => "créer un commercial"],
            ['name' => 'trash-commercial', 'description' => "archiver un commercial"],
            ['name' => 'restore-commercial', 'description' => "restaurer un commercial archivé"],
            ['name' => 'edit-commercial', 'description' => "modifier un commercial"],
            ['name' => 'show-commercial', 'description' => "afficher les informations détaillées d'un commercial"],
            ['name' => 'attribuate-commercial', 'description' => "attribuer un emplacement à un commercial"],
            ['name' => 'global-ouverture', 'description' => "afficher tout les ouvertures de caisse"],
            ['name' => 'own-ouverture', 'description' => "afficher uniquement les ouvertures de caisse crées par l'utilisateur connecté"],
            ['name' => 'create-ouverture', 'description' => "afficher les informations détaillées d'une ouverture de caisse"],
            ['name' => 'show-ouverture', 'description' => "afficher les informations détaillées d'une ouverture de caisse"],
            ['name' => 'global-fermeture', 'description' => "afficher tout les points de caisse"],
            ['name' => 'own-fermeture', 'description' => "afficher uniquement les points de caisse crées par l'utilisateur connecté"],
            ['name' => 'create-fermeture', 'description' => "créer un point de caisse"],
            ['name' => 'show-fermeture', 'description' => "afficher les informations détaillées d'un point de caisse"],
            ['name' => 'global-encaissement', 'description' => "afficher tout les encaissements"],
            ['name' => 'own-encaissement', 'description' => "afficher uniquement les encaissements crées par l'utilisateur connecté"],
            ['name' => 'create-encaissement', 'description' => "créer un encaissement"],
            ['name' => 'show-encaissement', 'description' => "afficher les informations détaillées d'un point de caisse"],
        ]);
        $permissions->each(fn($permission) => Permission::create($permission));
    }
}
