<?php

define('ANNEXE_FACTURE_PREFIXE', 'FAN');
define('EQUIPEMENT_FACTURE_PREFIXE', 'FEQ');
define('INITIALE_FACTURE_PREFIXE', 'FIN');
define('LOYER_FACTURE_PREFIXE', 'FAL');
define('PERSONNE_CODE_PREFIXE', 'PER');
define('CONTRAT_CODE_PREFIXE', 'CON');
define('ORDONNANCEMENT_CODE_PREFIXE', 'ORD');
define('FERMETURE_CODE_PREFIXE', 'FER');
define('COMMERCIAL_CODE_PREFIXE', 'COM');
define('BORDEREAU_CODE_PREFIXE', 'BOR');
define('ANNEXE_CODE_PREFIXE', 'NEX');
define('GUICHET_CODE_PREFIXE', 'GUI');
define('CAISSIER_CODE_PREFIXE', 'CAI');
define('OUVERTURE_CODE_PREFIXE', 'OUV');
define('MONTANT_TIMBRE', 100);
define('TEMPLATE_ANNEXE_PREFIXE', 'ANEX');
define('TEMPLATE_BAIL_PREFIXE', 'EMPL');
define('COLLECTION_MEDIA_LOGO', 'logo');
define('COLLECTION_MEDIA_CONTRAT_BAIL', 'bailgabari');
define('COLLECTION_MEDIA_CONTRAT_ANNEXE', 'annexegabari');
define('COLLECTION_MEDIA_CONTRAT', 'contrat');
define('COLLECTION_MEDIA_IDENTITE', 'identite');
define('COLLECTION_MEDIA_PHOTOCOPIE', 'photocopie');
define('SITUATION_MARIAGE', 'marier');
define('SITUATION_CONCUBINAGE', 'concubinage');
define('SITUATION_CELIBAT', 'celibataire');
