<?php

define('ANNEXE_FACTURE_PREFIXE', 'FAN');
define('EQUIPEMENT_FACTURE_PREFIXE', 'FEQ');
define('INITIALE_FACTURE_PREFIXE', 'FIN');
define('LOYER_FACTURE_PREFIXE', 'FAL');
define('PERSONNE_CODE_PREFIXE', 'PER');
define('CONTRAT_CODE_PREFIXE', 'CON');
define('ORDONNANCEMENT_CODE_PREFIXE', 'ORD');
define('COMMERCIAL_CODE_PREFIXE', 'COM');
define('BORDEREAU_CODE_PREFIXE', 'BOR');
