<?php

define('ANNEXE_FACTURE_PREFIXE', 'FAN');
define('EQUIPEMENT_FACTURE_PREFIXE', 'FEQ');
define('INITIALE_FACTURE_PREFIXE', 'FIN');
define('LOYER_FACTURE_PREFIXE', 'FAL');
define('PERSONNE_CODE_PREFIXE', 'PER');
define('CONTRAT_CODE_PREFIXE', 'CON');
define('ORDONNANCEMENT_CODE_PREFIXE', 'ORD');
define('COMMERCIAL_CODE_PREFIXE', 'COM');
define('BORDEREAU_CODE_PREFIXE', 'BOR');
define('ANNEXE_CODE_PREFIXE', 'NEX');
define('GUICHET_CODE_PREFIXE', 'GUI');
define('CAISSIER_CODE_PREFIXE', 'CAI');
define('OUVERTURE_CODE_PREFIXE', 'OUV');
