<?php

return [
    'utilisateur' => [
        'list-global' => 'global-user',
        'list-own' => 'own-user',
        'create' => 'create-user',
        'trash' => 'trash-user',
        'restore' => 'restore-user',
        'delete' => 'delete-user',
        'edit' => 'edit-user',
        'show' => 'show-user',
        'attribuate-role' => 'attribuate-role-user',
    ],
    'role' => [
        'list' => 'list-role',
        'create' => 'create-role',
        'trash' => 'trash-role',
        'restore' => 'restore-role',
        'delete' => 'delete-role',
        'edit' => 'edit-role',
    ],
    'permission' => [
        'list' => 'list-permission',
        'edit' => 'edit-permission',
    ],
    'configuration-dashboard' => [
        'structure' => 'structure-site',
    ],
    'site' => [
        'list-global' => 'global-site',
        'list-own' => 'own-site',
        'create' => 'create-site',
        'trash' => 'trash-site',
        'delete' => 'delete-site',
        'edit' => 'edit-site',
        'show' => 'show-site',
    ],
    'pavillon' => [
        'list-global' => 'global-pavillon',
        'list-own' => 'own-pavillon',
        'create' => 'create-pavillon',
        'trash' => 'trash-pavillon',
        'delete' => 'delete-pavillon',
        'edit' => 'edit-pavillon',
    ],
    'niveau' => [
        'list-global' => 'global-niveau',
        'list-own' => 'own-niveau',
        'create' => 'create-niveau',
        'trash' => 'trash-niveau',
        'delete' => 'delete-niveau',
        'edit' => 'edit-niveau',
    ],
    'zone' => [
        'list-global' => 'global-zone',
        'list-own' => 'own-zone',
        'create' => 'create-zone',
        'trash' => 'trash-zone',
        'restore' => 'restore-zone',
        'delete' => 'delete-zone',
        'edit' => 'edit-zone',
    ],
    'emplacement' => [
        'list-global' => 'global-emplacement',
        'list-own' => 'own-emplacement',
        'create' => 'create-emplacement',
        'trash' => 'trash-emplacement',
        'restore' => 'restore-emplacement',
        'delete' => 'delete-emplacement',
        'edit' => 'edit-emplacement',
        'show' => 'show-emplacement',
    ],
    'equipement' => [
        'list-global' => 'global-equipement',
        'list-own' => 'own-equipement',
        'create' => 'create-equipement',
        'trash' => 'trash-equipement',
        'restore' => 'restore-equipement',
        'delete' => 'delete-equipement',
        'edit' => 'edit-equipement',
    ],
    'abonnement' => [
        'list-global' => 'global-abonnement',
        'list-own' => 'own-abonnement',
        'create' => 'create-abonnement',
        'trash' => 'trash-abonnement',
        'delete' => 'delete-abonnement',
        'restore' => 'restore-abonnement',
        'abort' => 'abort-abonnement',
        'edit' => 'edit-abonnement',
        'show' => 'show-abonnement',
    ],
    'type-equipement' => [
        'list-global' => 'global-type-equipement',
        'list-own' => 'own-type-equipement',
        'create' => 'create-type-equipement',
        'restore' => 'restore-type-equipement',
        'trash' => 'trash-type-equipement',
        'delete' => 'delete-type-equipement',
        'edit' => 'edit-type-equipement',
    ],
    'type-emplacement' => [
        'list-global' => 'global-type-emplacement',
        'list-own' => 'own-type-emplacement',
        'create' => 'create-type-emplacement',
        'restore' => 'restore-type-emplacement',
        'trash' => 'trash-type-emplacement',
        'delete' => 'delete-type-emplacement',
        'edit' => 'edit-type-emplacement',
    ],
    'type-personne' => [
        'list-global' => 'global-type-personne',
        'list-own' => 'own-type-personne',
        'create' => 'create-type-personne',
        'restore' => 'restore-type-personne',
        'trash' => 'trash-type-personne',
        'delete' => 'delete-type-personne',
        'edit' => 'edit-type-personne',
    ],
    'service-annexe' => [
        'list-global' => 'global-annexe',
        'list-own' => 'own-annexe',
        'create' => 'create-annexe',
        'trash' => 'trash-annexe',
        'restore' => 'restore-annexe',
        'delete' => 'delete-annexe',
        'edit' => 'edit-annexe',
    ],
    'guichet' => [
        'list-global' => 'global-guichet',
        'list-own' => 'own-guichet',
        'create' => 'create-guichet',
        'restore' => 'restore-guichet',
        'trash' => 'trash-guichet',
        'delete' => 'delete-guichet',
        'edit' => 'edit-guichet',
    ],
    'caissier' => [
        'list-global' => 'global-caissier',
        'list-own' => 'own-caissier',
        'create' => 'create-caissier',
        'trash' => 'trash-caissier',
        'restore' => 'restore-caissier',
        'attribuate' => 'attribuate-caissier',
        'show' => 'show-caissier',
    ],
    'compte' => [
        'list-global' => 'global-compte',
        'list-own' => 'own-compte',
        'create' => 'create-compte',
        'edit' => 'edit-compte',
    ],
    'banque' => [
        'list-global' => 'global-banque',
        'list-own' => 'own-banque',
        'create' => 'create-banque',
        'trash' => 'trash-banque',
        'restore' => 'restore-banque',
        'delete' => 'delete-banque',
        'edit' => 'edit-banque',
    ],
    'application' => [
        'list' => 'list-application',
        'edit' => 'edit-application',
    ],
    'gabari-contrat' => [
        'list-global' => 'global-gabari-contrat',
        'list-own' => 'own-gabari-contrat',
        'create' => 'create-gabari-contrat',
        'trash' => 'trash-gabari-contrat',
        'delete' => 'delete-gabari-contrat',
        'edit' => 'edit-gabari-contrat',
        'show' => 'show-gabari-contrat',
    ],
    'reception-dashboard' => [
        'list' => 'list-reception-dashboard',
        'filter' => 'filter-reception-dashboard',
    ],
    'contrat' => [
        'list-global' => 'global-contrat',
        'list-own' => 'own-contrat',
        'create' => 'create-contrat',
        'trash' => 'trash-contrat',
        'restore' => 'restore-contrat',
        'delete' => 'delete-contrat',
        'edit' => 'edit-contrat',
        'schedule' => 'schedule-contrat',
        'endorse' => 'endorse-contrat',
        'validate' => 'validate-contrat',
        'show' => 'show-contrat',
        'list-valid-global' => 'global-contrat-valid',
        'list-valid-own' => 'own-contrat-valid',
        'valid-show' => 'show-contrat-valid',
    ],
    'personne' => [
        'list-global' => 'global-personne',
        'list-own' => 'own-personne',
        'trash' => 'trash-personne',
        'delete' => 'delete-personne',
        'restore' => 'restore-personne',
        'edit' => 'edit-personne',
        'show' => 'show-personne',
    ],
    'contrat-valide' => [
        'list-global' => 'global-contrat-valide',
        'list-own' => 'own-contrat-valide',
        'show' => 'show-contrat-valide',
    ],
    'ordonnancement-dashboard' => [
        'list' => 'list-ordonnancement-dashboard',
        'filter' => 'filter-ordonnancement-dashboard',
    ],
    'ordonnancement' => [
        'list-global' => 'global-ordonnancement',
        'list-own' => 'own-ordonnancement',
        'show' => 'show-ordonnancement',
    ],
    'facture-dashboard' => [
        'list' => 'list-facture-dashboard',
        'filter' => 'filter-facture-dashboard',
    ],
    'facture-equipement' => [
        'list-global' => 'global-facture-equipement',
        'list-own' => 'own-facture-equipement',
        'show' => 'show-facture-equipement',
    ],
    'facture-annexe' => [
        'list-global' => 'global-facture-annexe',
        'list-own' => 'own-facture-annexe',
        'show' => 'show-facture-annexe',
    ],
    'facture-initiale' => [
        'list-global' => 'global-facture-initiale',
        'list-own' => 'own-facture-initiale',
        'show' => 'show-facture-initiale',
        'edit' => 'edit-facture-initiale',
    ],
    'facture-loyer' => [
        'list-global' => 'global-facture-loyer',
        'list-own' => 'own-facture-loyer',
        'show' => 'show-facture-loyer',
    ],
    'bordereau-dashboard' => [
        'list' => 'list-bordereau-dashboard',
        'filter' => 'filter-bordereau-dashboard',
    ],
    'bordereau' => [
        'list-global' => 'global-bordereau',
        'list-own' => 'own-bordereau',
        'collect' => 'collect-bordereau',
        'edit' => 'edit-bordereau',
        'show' => 'show-bordereau',
    ],
    'commercial' => [
        'list-global' => 'global-commercial',
        'list-own' => 'own-commercial',
        'trash' => 'trash-commercial',
        'restore' => 'restore-commercial',
        'edit' => 'edit-commercial',
        'show' => 'show-commercial',
        'attribuate' => 'attribuate-commercial',
    ],
    'caisse-dashboard' => [
        'list' => 'list-caissier-dashboard',
        'filter' => 'filter-caissier-dashboard',
    ],
    'ouverture' => [
        'list-global' => 'global-ouverture',
        'list-own' => 'own-ouverture',
        'create' => 'create-ouverture',
        'show' => 'show-ouverture',
    ],
    'fermeture' => [
        'list-global' => 'global-fermeture',
        'list-own' => 'own-fermeture',
        'create' => 'create-fermeture',
        'show' => 'show-fermeture',
    ],
    'encaissement' => [
        'list-global' => 'global-encaissement',
        'list-own' => 'own-encaissement',
        'create' => 'create-encaissement',
        'close' => 'close-encaissement',
        'show' => 'show-encaissement',
    ],
];
