<?php

return [
    'utilisateur' => [
        'list-global' => 'global-user',
        'list-own' => 'own-user',
        'create' => 'create-user',
        'trash' => 'trash-user',
        'delete' => 'delete-user',
        'edit' => 'edit-user',
        'show' => 'show-user',
    ],
    'role' => [
        'list' => 'list-role',
        'create' => 'create-role',
        'trash' => 'trash-role',
        'delete' => 'delete-role',
        'edit' => 'edit-role',
    ],
    'permission' => [
        'list' => 'list-permission',
        'create' => 'create-permission',
        'trash' => 'trash-permission',
        'delete' => 'delete-permission',
        'edit' => 'edit-permission',
    ],
    'configuration-dashboard' => [
        'structure' => 'structure-site',
    ],
    'site' => [
        'list-global' => 'global-site',
        'list-own' => 'own-site',
        'create' => 'create-site',
        'trash' => 'trash-site',
        'delete' => 'delete-site',
        'edit' => 'edit-site',
    ],
    'pavillon' => [
        'list-global' => 'global-pavillon',
        'list-own' => 'own-pavillon',
        'create' => 'create-pavillon',
        'trash' => 'trash-pavillon',
        'delete' => 'delete-pavillon',
        'edit' => 'edit-pavillon',
    ],
    'niveau' => [
        'list-global' => 'global-niveau',
        'list-own' => 'own-niveau',
        'create' => 'create-niveau',
        'trash' => 'trash-niveau',
        'delete' => 'delete-niveau',
        'edit' => 'edit-niveau',
    ],
    'zone' => [
        'list-global' => 'global-zone',
        'list-own' => 'own-zone',
        'create' => 'create-zone',
        'trash' => 'trash-zone',
        'delete' => 'delete-zone',
        'edit' => 'edit-zone',
    ],
    'emplacement' => [
        'list-global' => 'global-emplacement',
        'list-own' => 'own-emplacement',
        'create' => 'create-emplacement',
        'trash' => 'trash-emplacement',
        'delete' => 'delete-emplacement',
        'edit' => 'edit-emplacement',
    ],
    'equipement' => [
        'list-global' => 'global-equipement',
        'list-own' => 'own-equipement',
        'create' => 'create-equipement',
        'trash' => 'trash-equipement',
        'delete' => 'delete-equipement',
        'edit' => 'edit-equipement',
    ],
    'abonnement' => [
        'list-global' => 'global-abonnement',
        'list-own' => 'own-abonnement',
        'create' => 'create-abonnement',
        'trash' => 'trash-abonnement',
        'delete' => 'delete-abonnement',
        'restore' => 'restore-abonnement',
        'abort' => 'abort-abonnement',
        'edit' => 'edit-abonnement',
    ],
    'type-equipement' => [
        'list-global' => 'global-type-equipement',
        'list-own' => 'own-type-equipement',
        'create' => 'create-type-equipement',
        'trash' => 'trash-type-equipement',
        'delete' => 'delete-type-equipement',
        'edit' => 'edit-type-equipement',
    ],
    'type-emplacement' => [
        'list-global' => 'global-type-emplacement',
        'list-own' => 'own-type-emplacement',
        'create' => 'create-type-emplacement',
        'trash' => 'trash-type-emplacement',
        'delete' => 'delete-type-emplacement',
        'edit' => 'edit-type-emplacement',
    ],
    'service-annexe' => [
        'list-global' => 'global-annexe',
        'list-own' => 'own-annexe',
        'create' => 'create-annexe',
        'trash' => 'trash-annexe',
        'delete' => 'delete-annexe',
        'edit' => 'edit-annexe',
    ],
    'guichet' => [
        'list-global' => 'global-guichet',
        'list-own' => 'own-guichet',
        'create' => 'create-guichet',
        'trash' => 'trash-guichet',
        'delete' => 'delete-guichet',
        'edit' => 'edit-guichet',
    ],
    'caissier' => [
        'list-global' => 'global-caissier',
        'list-own' => 'own-caissier',
        'create' => 'create-caissier',
        'trash' => 'trash-caissier',
        'delete' => 'delete-caissier',
        'attribuate' => 'attribuate-caissier',
        'edit' => 'edit-caissier',
        'show' => 'show-caissier',
    ],
    'compte' => [
        'list-global' => 'global-compte',
        'list-own' => 'own-compte',
        'create' => 'create-compte',
        'trash' => 'trash-compte',
        'delete' => 'delete-compte',
        'edit' => 'edit-compte',
    ],
    'banque' => [
        'list-global' => 'global-banque',
        'list-own' => 'own-banque',
        'create' => 'create-banque',
        'trash' => 'trash-banque',
        'restore' => 'restore-banque',
        'delete' => 'delete-banque',
        'edit' => 'edit-banque',
    ],
    'application' => [
        'list' => 'list-application',
        'edit' => 'edit-application',
    ],
    'gabari-contrat' => [
        'list-global' => 'global-gabari-contrat',
        'list-own' => 'own-gabari-contrat',
        'create' => 'create-gabari-contrat',
        'trash' => 'trash-gabari-contrat',
        'delete' => 'delete-gabari-contrat',
        'edit' => 'edit-gabari-contrat',
        'show' => 'show-gabari-contrat',
    ],
    'reception-dashboard' => [
        'list' => 'list-reception-dashboard',
        'filter' => 'filter-reception-dashboard',
    ],
    'demande' => [
        'bail' => [
            'list-global' => 'global-demande-bail',
            'list-own' => 'own-demande-bail',
            'create' => 'create-demande-bail',
            'trash' => 'trash-demande-bail',
            'delete' => 'delete-demande-bail',
            'edit' => 'edit-demande-bail',
            'schedule' => 'schedule-demande-bail',
            'endorse' => 'endorse-demande-bail',
            'validate' => 'validate-demande-bail',
            'show' => 'show-demande-bail',
        ],
        'annexe' => [
            'list-global' => 'global-demande-annexe',
            'list-own' => 'own-demande-annexe',
            'create' => 'create-demande-annexe',
            'trash' => 'trash-demande-annexe',
            'delete' => 'delete-demande-annexe',
            'edit' => 'edit-demande-annexe',
            'schedule' => 'schedule-demande-annexe',
            'endorse' => 'endorse-demande-annexe',
            'validate' => 'validate-demande-annexe',
            'show' => 'show-demande-annexe',
        ],
    ],
    'prospect' => [
        'list-global' => 'global-prospect',
        'list-own' => 'own-prospect',
        'create' => 'create-prospect',
        'trash' => 'trash-prospect',
        'delete' => 'delete-prospect',
        'edit' => 'edit-prospect',
        'show' => 'show-prospect',
    ],
    'client' => [
        'list-global' => 'global-client',
        'list-own' => 'own-client',
        'trash' => 'trash-client',
        'delete' => 'delete-client',
        'edit' => 'edit-client',
        'show' => 'show-client',
    ],
    'contrat-valide' => [
        'list-global' => 'global-contrat-valide',
        'list-own' => 'own-contrat-valide',
        'show' => 'show-contrat-valide',
    ],
    'ordonnancement-dashboard' => [
        'list' => 'list-ordonnancement-dashboard',
        'filter' => 'filter-ordonnancement-dashboard',
    ],
    'ordonnancement' => [
        'list-global' => 'global-ordonnancement',
        'list-own' => 'own-ordonnancement',
        'show' => 'show-ordonnancement',
    ],
    'facture-dashboard' => [
        'list' => 'list-facture-dashboard',
        'filter' => 'filter-facture-dashboard',
    ],
    'facture-equipement' => [
        'list-global' => 'global-facture-equipement',
        'list-own' => 'own-facture-equipement',
        'show' => 'show-facture-equipement',
    ],
    'facture-annexe' => [
        'list-global' => 'global-facture-annexe',
        'list-own' => 'own-facture-annexe',
        'show' => 'show-facture-annexe',
    ],
    'facture-initiale' => [
        'list-global' => 'global-facture-initiale',
        'list-own' => 'own-facture-initiale',
        'show' => 'show-facture-initiale',
        'edit' => 'edit-facture-initiale',
    ],
    'facture-soldees' => [
        'list-global' => 'global-facture-soldees',
        'list-own' => 'own-facture-soldees',
        'show' => 'show-facture-soldees',
    ],
    'bordereau-dashboard' => [
        'list' => 'list-bordereau-dashboard',
        'filter' => 'filter-bordereau-dashboard',
    ],
    'bordereau' => [
        'list-global' => 'global-bordereau',
        'list-own' => 'own-bordereau',
        'edit' => 'edit-bordereau',
        'show' => 'show-bordereau',
    ],
    'commercial' => [
        'list-global' => 'global-commercial',
        'list-own' => 'own-commercial',
        'trash' => 'trash-commercial',
        'edit' => 'edit-commercial',
        'show' => 'show-commercial',
        'attribuate' => 'attribuate-commercial',
    ],
    'caisse-dashboard' => [
        'list' => 'list-caissier-dashboard',
        'filter' => 'filter-caissier-dashboard',
    ],
    'ouverture' => [
        'list-global' => 'global-ouverture',
        'list-own' => 'own-ouverture',
        'show' => 'show-ouverture',
    ],
    'point-caisse' => [
        'list-global' => 'global-point-caisse',
        'list-own' => 'own-point-caisse',
        'show' => 'show-point-caisse',
    ],
    'encaissement' => [
        'list-global' => 'global-encaissement',
        'list-own' => 'own-encaissement',
        'show' => 'show-encaissement',
    ],
];
